//! Rust FFI bindings for OpenSSL (libssl + libcrypto).
//!
//! Generated by `bnd-openssl-gen` — do not edit `src/openssl/` manually.
//!
//! ## Feature-gated modules
//!
//! Each OpenSSL partition is a separate Cargo feature:
//!
//! - **`types`** — opaque type forward declarations (`EVP_MD`, `SSL`, `BIO`, etc.)
//! - **`crypto`** — library version and core utilities
//! - **`rand`** — random number generation

pub mod openssl;
